### ISSUE TITLE
EnvVarMap indices are non-deterministic

### ISSUE THREAD

**Issue by aeneasr** [GoogleContainerTools/skaffold#2680]
### Expected behavior

When building multiple artifacts, the indices appended to `DIGEST(_*)` and `IMAGE_NAME` behave unexpectedly which makes it impossible to use multiple build artifacts in combination with e.g. `deploy.helm.releases.*.setValueTemplates`.

Unfortunately, I still have to rely on `setValueTemplates` because the `helm` imageStrategy seems to be broken (several issues open for it).

### Actual behavior

I would expect `DIGEST` and `DIGEST2` AND `DIGEST<n>` to always refer to the same build artifact. However output from `EnvVarMap`  is not deterministic and deployments fail after a couple of rebuilds. I'm guessing that the more images we have, the frequency of this will increase:

```
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "IMAGE_NAME":"gcr.io/ory-artifacts/console"}
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST2":"6a3fdeb-dirty@sha256:f40a6d87dac23fbb312ea494ea6e0c74ef03da7a6d15922131dc1bb71c8bf3de", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_ALGO2":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST_HEX2":"f40a6d87dac23fbb312ea494ea6e0c74ef03da7a6d15922131dc1bb71c8bf3de", "IMAGE_NAME":"gcr.io/ory-artifacts/console", "IMAGE_NAME2":"gcr.io/ory-artifacts/oathkeeper"}
```

```
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "IMAGE_NAME":"gcr.io/ory-artifacts/oathkeeper"}
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "DIGEST2":"6a3fdeb-dirty@sha256:0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_ALGO2":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "DIGEST_HEX2":"0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "IMAGE_NAME":"gcr.io/ory-artifacts/oathkeeper", "IMAGE_NAME2":"gcr.io/ory-artifacts/console"}
```

So, as you can see above, `IMAGE_NAME<n>` switches around:

```
 "IMAGE_NAME":"gcr.io/ory-artifacts/oathkeeper", "IMAGE_NAME2":"gcr.io/ory-artifacts/console"
```

vs

```
"IMAGE_NAME":"gcr.io/ory-artifacts/console", "IMAGE_NAME2":"gcr.io/ory-artifacts/oathkeeper"
```

I think it's generally awkward that Skaffold uses a different naming strategy for helm than supported by probably 95% of helm projects out there. And there's very little documentation that helps with that.

### Information

- Skaffold version: v0.36.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    useDockerCLI: false
  artifacts:
    # The order of these needs to stay the same
    -
      image: gcr.io/ory-artifacts/console
      context: console
      docker:
        dockerfile: Dockerfile-skaffold
    -
      image: gcr.io/ory-artifacts/oathkeeper
      context: skaffold/oathkeeper
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    flags:
      global: ["--tiller-namespace","backoffice"]
    releases:
      -
        name: console
        chartPath: helm/charts/console
        namespace: backoffice
        recreatePods: true
        valuesFiles:
          - skaffold/console/values.yaml
        setValueTemplates:
          image.repository: gcr.io/ory-artifacts/console
          image.tag: "{{.DIGEST}}"
      -
        name: oathkeeper
        chartPath: ory/oathkeeper
        namespace: backoffice
        remote: true # required for remote charts
        skipBuildDependencies: true # required for remote charts
        recreatePods: true
        valuesFiles:
          - skaffold/oathkeeper/values.yaml
        setValueTemplates:
          image.repository: gcr.io/ory-artifacts/oathkeeper
          image.tag: "{{.DIGEST2}}"
```

### Steps to reproduce the behavior

Since all of these a private it's kinda tricky to reproduce this but I might be able to come up with something if required.

**Comment by balopat** [comment]
Thank you for digging deep and writing all this up! We should look into this as soon as we can, this is definitely a bug that makes hard to build reproducibly if users depend on these values. I see in #2681 that you discovered `imageStrategy:helm` - we should fix this nevertheless but - if you use `helm` imageStrategy, do you still need this?

**Comment by aeneasr** [comment]
No, since the helm imageStrategy works now I do not personally rely on this any more. I'm pretty sure it's being caused by either some map -> slice conversion (as maps are non-deterministic) or by the yaml decoder itself (although I kinda doubt that)

Thank you for the super-fast replies 👍

**Comment by balopat** [comment]
Great, thank you! 

Bumping down to p1 as using `imageStrategy:helm` is probably satisfactory for most users, i.e. there is a workaround.

**Comment by dgageot** [comment]
OK, I found the issue. In dev mode, the order of the artifacts is changed based on which one was rebuilt. Let me fix that!

**Comment by aeneasr** [comment]
This is still broken on 0.40.0. While it's true that the indices no longer randomly switch around _while skaffold is watching/rebuilding images_, they are still randomly chosen when skaffold is started.

**Comment by aeneasr** [comment]
Nevermind - I think it was related to a messy/broken cleanup. I can't seem to be able to reproduce the issue any more :)

**Comment by aeneasr** [comment]
Sorry for the spam, but this is indeed still an issue. I believe that if you start `skaffold dev` with one of the images requiring a rebuild, then the order is messed up. If no image requires a rebuild on boot, then the order is correct.

**Comment by dgageot** [comment]
Let me reopen the ticket.

**Comment by aeneasr** [comment]
Thank you for the quick response - happy to provide more context if required, but we've observed this issue now several times so I'M fairly confident that rebuilding the image on skaffold start up causes the order issue. My gut says that changes applied in #2761 are probably missing in the initial build phase.

To make things a bit more clear, assuming the config from the opening post:

1. Make changes to `skaffold/oathkeeper/Dockerfile`
2. Run `skaffold dev`
3. `DIGEST2` is not deterministic

1. Run `skaffold dev`
2. Make changes to `skaffold/oathkeeper/Dockerfile`
3. `DIGEST2` is behaving as expected and deterministic

We're now using more artifacts than originally, but the layout is pretty much the same. It's possible that with more artifacts the issue will appear more frequently because the chance is higher that the order is not kept (most likely due to a map being used somewhere).

**Comment by dgageot** [comment]
OK, thanks a lot for all the details! I think I found the issue. Can you run with `--cache-artifacts=false` and see if it's better? I'll push a fix today

**Comment by aeneasr** [comment]
Awesome! I will try with cache set to false over the day today and see if the issue is fixed :)

**Comment by aeneasr** [comment]
I can confirm that `--cache-artifacts=false` results in predictable builds, so IMO your analysis is correct :) Thank you for investigating! Since disabling caching is fairly slow I would be super happy to see this in the next Skaffold release!

And honestly, so nice to see super quick responses and bug fixes. Skaffold is beyond anything we've imagined 3-4 years ago!

**Comment by dgageot** [comment]
Thank you @aeneasr!
