### ISSUE TITLE
V2 Fix `TestHelmRender`

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7285]
Test log:
```
=== RUN   TestHelmRender/Bare_bones_render
panic: test timed out after 50m0s

goroutine 651 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1788 +0x8e
created by time.goFunc
	/opt/hostedtoolcache/go/1.17.8/x64/src/time/sleep.go:180 +0x31

goroutine 1 [chan receive, 34 minutes]:
testing.(*T).Run(0xc000829040, {0x27f9052, 0x46dbd3}, 0x2a86a78)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1307 +0x375
testing.runTests.func1(0xc0008515c0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1598 +0x6e
testing.tRunner(0xc000829040, 0xc00081fd18)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1259 +0x102
testing.runTests(0xc000420800, {0x4332120, 0x57, 0x57}, {0x48d50d, 0x27fa1fc, 0x434f400})
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1596 +0x43f
testing.(*M).Run(0xc000420800)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1504 +0x51d
main.main()
	_testmain.go:215 +0x14b

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.20.0/klog.go:1181 +0x6a
created by k8s.io/klog/v2.init.0
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.20.0/klog.go:420 +0xfb

goroutine 22 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000aa480)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92

goroutine 23 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0)
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1c5

goroutine 24 [chan receive, 50 minutes]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.newHandler.func1()
	/home/runner/work/skaffold/skaffold/pkg/skaffold/event/v2/event.go:61 +0x48
created by github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.newHandler
	/home/runner/work/skaffold/skaffold/pkg/skaffold/event/v2/event.go:59 +0x107

goroutine 7 [chan receive, 50 minutes]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event.newHandler.func1()
	/home/runner/work/skaffold/skaffold/pkg/skaffold/event/event.go:60 +0x45
created by github.com/GoogleContainerTools/skaffold/pkg/skaffold/event.newHandler
	/home/runner/work/skaffold/skaffold/pkg/skaffold/event/event.go:58 +0xcf

goroutine 51 [IO wait, 42 minutes]:
internal/poll.runtime_pollWait(0x7fc1b13bbbe0, 0x72)
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00077a180, 0xc001010000, 0x0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00077a180, {0xc001010000, 0xe826, 0xe826})
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00077a180, {0xc001010000, 0xc001010005, 0x1011})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0000100d0, {0xc001010000, 0x6, 0xc00008a7f8})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000b8ffe0, {0xc001010000, 0x0, 0x40bced})
	/opt/hostedtoolcache/go/1.17.8/x64/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00050d078, {0x2ceaaa0, 0xc000b8ffe0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00050ce00, {0x2cf3fa0, 0xc0000100d0}, 0xe826)
	/opt/hostedtoolcache/go/1.17.8/x64/src/crypto/tls/conn.go:[799](https://github.com/GoogleContainerTools/skaffold/runs/5891793427?check_suite_focus=true#step:16:799) +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00050ce00, 0x0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00050ce00, {0xc0005ae000, 0x1000, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/crypto/tls/conn.go:1277 +0x16f
net/http.(*persistConn).Read(0xc000718240, {0xc0005ae000, 0xc000102d80, 0xc00008ad30})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc000121980)
	/opt/hostedtoolcache/go/1.17.8/x64/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc000121980, 0x1)
	/opt/hostedtoolcache/go/1.17.8/x64/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc000718240)
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:1747 +0x1e05

goroutine 173 [select, 4 minutes]:
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000b6b9f8, 0x0, 0xc0009f8900)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:539 +0xef
k8s.io/apimachinery/pkg/util/wait.PollUntil(0xc0000257b8, 0x5684e5, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:492 +0x8c
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0xc0000257d0, 0xc0003dcba0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:511 +0x75
created by k8s.io/client-go/transport.(*dynamicClientCert).Run
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/transport/cert_rotation.go:142 +0x326

goroutine 648 [chan receive, 34 minutes]:
testing.(*T).Run(0xc0001e09c0, {0x2[800](https://github.com/GoogleContainerTools/skaffold/runs/5891793427?check_suite_focus=true#step:16:800)005, 0x40f307}, 0xc0004b3df0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1307 +0x375
github.com/GoogleContainerTools/skaffold/testutil.Run(0xc0001e09c0, {0x2800005, 0xc000ebfec0}, 0xc0004b3de0)
	/home/runner/work/skaffold/skaffold/testutil/util.go:253 +0x93
github.com/GoogleContainerTools/skaffold/integration.TestHelmRender(0xc000aad200)
	/home/runner/work/skaffold/skaffold/integration/render_test.go:413 +0x331
testing.tRunner(0xc0001e09c0, 0x2a86a78)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1306 +0x35a

goroutine 10 [chan receive, 50 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc000471260, 0x6)
	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/tree_nonrecursive.go:36 +0x49
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/tree_nonrecursive.go:29 +0x16f

goroutine 11 [chan receive, 50 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc000471260, 0xc000471200)
	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/tree_nonrecursive.go:81 +0x5a
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.3-0.20201210012515-e2a77dcc14cf/tree_nonrecursive.go:30 +0x1c8

goroutine 52 [select, 42 minutes]:
net/http.(*persistConn).writeLoop(0xc000718240)
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/http/transport.go:1748 +0x1e65

goroutine 175 [select, 4 minutes]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:588 +0x19b
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:571 +0xba

goroutine 174 [select, 44 minutes]:
k8s.io/apimachinery/pkg/util/wait.contextForChannel.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:279 +0x77
created by k8s.io/apimachinery/pkg/util/wait.contextForChannel
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:278 +0xc8

goroutine 183 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000a5c900)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/util/workqueue/delaying_queue.go:231 +0x34e
created by k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/util/workqueue/delaying_queue.go:68 +0x23b

goroutine 184 [chan receive, 44 minutes]:
k8s.io/client-go/transport.(*dynamicClientCert).Run(0xc000162b40, 0xc000102a80)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/transport/cert_rotation.go:147 +0x335
created by k8s.io/client-go/transport.(*tlsTransportCache).get
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/transport/cache.go:104 +0x485

goroutine 172 [sync.Cond.Wait, 4 minutes]:
sync.runtime_notifyListWait(0xc000162b10, 0x8)
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0x2d1fcd0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/sync/cond.go:56 +0x8c
k8s.io/client-go/util/workqueue.(*Type).Get(0xc000a5c7e0)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/util/workqueue/queue.go:151 +0x9e
k8s.io/client-go/transport.(*dynamicClientCert).processNextWorkItem(0xc000162b40)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/transport/cert_rotation.go:156 +0x58
k8s.io/client-go/transport.(*dynamicClientCert).runWorker(...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/transport/cert_rotation.go:151
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fc1b0171358)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000cbcfc0, {0x2cf3a00, 0xc000c80c60}, 0x1, 0xc000102a80)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000807fb8, 0x3b9aca00, 0x0, 0xf8, 0x4414c5)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc000807fd0, 0x56846d, 0xc0006dfc00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.6/pkg/util/wait/wait.go:90 +0x25
created by k8s.io/client-go/transport.(*dynamicClientCert).Run
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.6/transport/cert_rotation.go:140 +0x26f

goroutine 230 [runnable]:
google.golang.org/grpc.(*clientStream).RecvMsg(0xc000763d00, {0x25e1000, 0xc000faad70})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/stream.go:816 +0x395
github.com/GoogleContainerTools/skaffold/proto/v1.(*skaffoldServiceEventLogClient).Recv(0xc0003dd750)
	/home/runner/work/skaffold/skaffold/proto/v1/skaffold_grpc.pb.go:83 +0x4c
github.com/GoogleContainerTools/skaffold/integration.apiEvents.func1()
	/home/runner/work/skaffold/skaffold/integration/rpc_test.go:424 +0x4a
created by github.com/GoogleContainerTools/skaffold/integration.apiEvents
	/home/runner/work/skaffold/skaffold/integration/rpc_test.go:422 +0x10f

goroutine 675 [select, 34 minutes]:
os/exec.(*Cmd).Start.func2()
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:449 +0x7b
created by os/exec.(*Cmd).Start
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:448 +0x7ef

goroutine 672 [syscall, 34 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x6953, 0xc000d3b688, 0x1000004, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/syscall/asm_linux_amd64.s:43 +0x5
os.(*Process).blockUntilWaitable(0xc000c1c2d0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/wait_waitid.go:33 +0x9c
os.(*Process).wait(0xc000c1c2d0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec_unix.go:23 +0x28
os.(*Process).Wait(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc000afa580)
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:507 +0x54
os/exec.(*Cmd).Run(0xc000710580)
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:341 +0x39
github.com/GoogleContainerTools/skaffold/pkg/skaffold/util.(*Commander).RunCmd(0x27e5284, {0x2d4c7f0, 0xc000136000}, 0xc000afa580)
	/home/runner/work/skaffold/skaffold/pkg/skaffold/util/cmd.go:105 +0x9d
github.com/GoogleContainerTools/skaffold/pkg/skaffold/util.RunCmd(...)
	/home/runner/work/skaffold/skaffold/pkg/skaffold/util/cmd.go:65
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/helm.(*Deployer).exec(0xc000afa2c0, {0x2d4c7f0, 0xc000136000}, {0x2cea860, 0xc00075ec90}, 0x0, {0xc000418d80, 0x6b, 0xd8}, {0xc000400120, ...})
	/home/runner/work/skaffold/skaffold/pkg/skaffold/deploy/helm/util.go:228 +0x58b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/helm.(*Deployer).Render(0xc000afa2c0, {0x2d4c7f0, 0xc000136000}, {0x2cea860, 0xc00075e5d0}, {0xc0008d4160, 0x33fd2c2, 0x1}, 0x74, {0x0, ...})
	/home/runner/work/skaffold/skaffold/pkg/skaffold/deploy/helm/helm.go:430 +0xb5c
github.com/GoogleContainerTools/skaffold/integration.TestHelmRender.func1(0xc000[805](https://github.com/GoogleContainerTools/skaffold/runs/5891793427?check_suite_focus=true#step:16:805)f18)
	/home/runner/work/skaffold/skaffold/integration/render_test.go:429 +0x25c
github.com/GoogleContainerTools/skaffold/testutil.Run.func1(0xc000829ba0)
	/home/runner/work/skaffold/skaffold/testutil/util.go:254 +0x59
testing.tRunner(0xc000829ba0, 0xc0004b3df0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1306 +0x35a

goroutine 674 [IO wait, 34 minutes]:
internal/poll.runtime_pollWait(0x7fc1b13bb840, 0x72)
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000400240, 0xc0004dd600, 0x1)
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000400240, {0xc0004dd600, 0x200, 0x200})
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/file_posix.go:32
os.(*File).Read(0xc000010208, {0xc0004dd600, 0x0, 0xc0000226a0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/file.go:119 +0x5e
bytes.(*Buffer).ReadFrom(0xc00075ec90, {0x2cf43c0, 0xc000010208})
	/opt/hostedtoolcache/go/1.17.8/x64/src/bytes/buffer.go:204 +0x98
io.copyBuffer({0x2cea860, 0xc00075ec90}, {0x2cf43c0, 0xc000010208}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/io/io.go:409 +0x14b
io.Copy(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/io/io.go:382
os/exec.(*Cmd).writerDescriptor.func1()
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0x0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:441 +0x25
created by os/exec.(*Cmd).Start
	/opt/hostedtoolcache/go/1.17.8/x64/src/os/exec/exec.go:440 +0x80d

goroutine 385 [runnable]:
google.golang.org/grpc.toRPCErr({0x2cf29a0, 0xc000010040})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/rpc_util.go:849 +0x3af
google.golang.org/grpc.(*csAttempt).recvMsg(0xc0002d3080, {0x25e1000, 0xc00135a640}, 0xc000ec3eb8)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/stream.go:983 +0x3ad
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0x203000)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/stream.go:826 +0x25
google.golang.org/grpc.(*clientStream).withRetry(0xc000aad200, 0xc000ec3f40, 0xc000ec3f10)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/stream.go:680 +0x2f6
google.golang.org/grpc.(*clientStream).RecvMsg(0xc000aad200, {0x25e1000, 0xc00135a640})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/stream.go:[825](https://github.com/GoogleContainerTools/skaffold/runs/5891793427?check_suite_focus=true#step:16:825) +0x11f
github.com/GoogleContainerTools/skaffold/proto/v1.(*skaffoldServiceEventLogClient).Recv(0xc00032b670)
	/home/runner/work/skaffold/skaffold/proto/v1/skaffold_grpc.pb.go:83 +0x4c
github.com/GoogleContainerTools/skaffold/integration.apiEvents.func1()
	/home/runner/work/skaffold/skaffold/integration/rpc_test.go:424 +0x4a
created by github.com/GoogleContainerTools/skaffold/integration.apiEvents
	/home/runner/work/skaffold/skaffold/integration/rpc_test.go:422 +0x10f
FAIL	github.com/GoogleContainerTools/skaffold/integration	3000.070s
```

**Comment by MarlonGamez** [comment]
The issue here revolves around using the post renderer field. Since we find the skaffold binary by running `os.Executable`, in a test environment this ends up being the test executable. So then we end up running something like this:
```
helm --kube-context  template gke-loadbalancer testdata/gke_loadbalancer/loadbalancer-helm --post-renderer /var/folders/wn/hkh84fg542dfgrmkjzwmgqdh00jl6c/T/go-build182753142/b391/integration.test
```
which includes an incorrect executable.

These tests will probably need to be updated to run the entire skaffold binary, rather than just creating a helm deployer and running render on those

**Comment by tejal29** [comment]
@ericzzzzzzz to verify. Should be fixed by https://github.com/GoogleContainerTools/skaffold/pull/7350

**Comment by ericzzzzzzz** [comment]
Hi @tejal29 , the test is still running with the same error, and #7350 seems unrelated by the way. 

```bash
=== RUN   TestDevSyncDefaultNamespace/manual_sync_with_polling_trigger
    helper.go:259: Running [skaffold build -f skaffold-manual.yaml --default-repo gcr.io/k8s-skaffold] in testdata/file-sync
    helper.go:259: Ran [skaffold build -f skaffold-manual.yaml --default-repo gcr.io/k8s-skaffold] in 1.273 second
    sync_test.go:97: Running [skaffold dev -f skaffold-manual.yaml --default-repo gcr.io/k8s-skaffold --trigger polling] in testdata/file-sync
time="2022-05-09T12:01:15-07:00" level=info msg="Waiting for pods [test-file-sync] to be ready" subtask=-1 task=DevLoop
time="2022-05-09T12:01:15-07:00" level=info msg="Still waiting for pods [test-file-sync]" subtask=-1 task=DevLoop
time="2022-05-09T12:01:16-07:00" level=warning msg="k8s/*.yaml did not match any file" subtask=-1 task=DevLoop
time="2022-05-09T12:01:16-07:00" level=warning msg="k8s/*.yaml did not match any file" subtask=-1 task=DevLoop
nothing to deploy
    helper.go:245: Ran [skaffold dev -f skaffold-manual.yaml --default-repo gcr.io/k8s-skaffold --trigger polling] in 1.178 second
```

**Comment by tejal29** [comment]
@ericzzzzzzz Sorry for the late responce. Can you convert the config to use new style manifests for all the testdata examples and give it a try?

```
git diff 
diff --git a/integration/testdata/gke_loadbalancer/skaffold.yaml b/integration/testdata/gke_loadbalancer/skaffold.yaml
index 404d9b4cf..f0078a274 100644
--- a/integration/testdata/gke_loadbalancer/skaffold.yaml
+++ b/integration/testdata/gke_loadbalancer/skaffold.yaml
@@ -4,7 +4,7 @@ build:
   artifacts:
     - image: gke-loadbalancer
       context: ./
-deploy:
+manifests:
   helm:
     releases:
     # seed test namespace in the release name.
(END)


```

**Comment by ericzzzzzzz** [comment]
@tejal29 sure

**Comment by ericzzzzzzz** [comment]
Hi @tejal29 TestHelmRender/Bare_bones_render test is still hanging there after updating skaffold.yaml, also it seems that the test doesn't need skaffold.yaml file and not use it.

**Comment by tejal29** [comment]
Lets meet in person and figure this out.

**Comment by tejal29** [comment]
> The issue here revolves around using the post renderer field. Since we find the skaffold binary by running `os.Executable`, in a test environment this ends up being the test executable. So then we end up running something like this:
> 
> ```
> helm --kube-context  template gke-loadbalancer testdata/gke_loadbalancer/loadbalancer-helm --post-renderer /var/folders/wn/hkh84fg542dfgrmkjzwmgqdh00jl6c/T/go-build182753142/b391/integration.test
> ```
> 
> which includes an incorrect executable.
> 
> These tests will probably need to be updated to run the entire skaffold binary, rather than just creating a helm deployer and running render on those, or I will override the value returned by `os.Executable`. Although I'm not sure if that's how we want to handle this integration test

@MarlonGamez you recommended a solution here. Would you able to pair with @ericzzzzzzz here?
