### ISSUE TITLE
Location of Skaffold schemas for IDE

### ISSUE THREAD

**Issue by seagullmouse** [GoogleContainerTools/skaffold#8615]
### Expected behavior
Provide a URL for schemas that can be passed into IntelliJ IDE

### Actual behavior
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/1561613/228868373-19d75249-d9f7-4b92-8d60-7bb582c2987d.png">

<img width="995" alt="image" src="https://user-images.githubusercontent.com/1561613/228868506-60e00f86-ed89-41d6-b286-3b9666b7e50e.png">

Every URL I have tried seems to fail. 

Please advise which URL to use.

**Comment by aaron-prindle** [comment]
@seagullmouse thanks for bringing this to our attention.  Cloud Code should have this schema bundled so I will notify that team to fix this on their end but we also host the schemas in our Github repo at:

`v4beta4.json schema`
https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/docs-v2/content/en/schemas/v4beta4.json

To view other schemas, see:
https://github.com/GoogleContainerTools/skaffold/tree/main/docs-v2/content/en/schemas

**Comment by seagullmouse** [comment]
Thanks for the reply.

Might be something wrong with my IntelliJ set up.

I've added the schema
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1561613/229135163-cce52110-dd33-4d50-bcc7-92a821c956d1.png">


But still see the IntelliJ warning
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/1561613/229135337-4a3d33d3-5564-4575-91f5-8617d09c392f.png">


Any ideas or should I wait to see if Cloud Code send an update?

**Comment by ivanporty** [comment]
@seagullmouse it looks like you have Jetbrains Kubernetes plugin installed which tries to treat this file as a Kubernetes resource. Try adding `#noK8s` annotation on top of the file and let us know if this fixes the problem.

Do you see Cloud Code generated documentation and completions on other fields in YAML? It seems so since there are no errors on other fields.

**Comment by seagullmouse** [comment]
- Adding `#noK8s` makes no difference.
- The other fields link through to v3 of the schema
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/1561613/230050826-b2bd78da-6c0c-4077-b7b0-b901b688b4c0.png">

What type of resource should I associate this file with? E.g. I could set up a rule then associates files named `skaffold.yaml` as Google Cloud or Skaffold but I don't see those options.

**Comment by aaron-prindle** [comment]
@ivanporty did you have additional information here related to the above?  Thanks

**Comment by ivanporty** [comment]
I see, we are not up to date yet with the schema, we'll update with the next release.

To add the new schema manually, you need to use IntelliJ schema settings, not Cloud Code. They are in the lower right corner of the IDE window by default (you will see v3.json there):

<img width="340" alt="Screen Shot 2023-04-17 at 8 49 20 PM" src="https://user-images.githubusercontent.com/11686100/232640799-a8a88849-86ff-4345-b889-cdaefbc420a2.png">

Click it, use `Add/Edit schema settings` and add new schema using URL above (https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/docs-v2/content/en/schemas/v4beta4.json). This should fix the warnings you see.

**Comment by seagullmouse** [comment]
Could this lack of compatibility with v4beta4 also be the reason that I can't use the Cloud Code: Kubernetes run configuration?

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/1561613/235165904-4e82bbea-250b-49d0-a6d9-119ef52d0712.png">

_"Invalid Data: Unable to read your skaffold.yaml config file. Check that it is properly formed, and ensure that a profile is selected on the Build/Deploy tab."_

I am able to run everything fine from the command line so my skaffold config appears to be fine.

**Comment by aaron-prindle** [comment]
@ivanporty, do you have any insights as to the root cause of what might be happening above?

@seagullmouse can you output what version of skaffold is being used by Cloud Code?

**Comment by seagullmouse** [comment]
skaffold version
v2.9.0

**Comment by seagullmouse** [comment]
This is still an issue with latest versions of Skaffold and IntelliJ.

<img width="960" alt="image" src="https://github.com/GoogleContainerTools/skaffold/assets/1561613/3a0d9e70-1fa9-49ab-8315-a71510165157">

It seems to ignore my custom added schemas

<img width="1489" alt="image" src="https://github.com/GoogleContainerTools/skaffold/assets/1561613/55e0ce22-a2a7-4fcc-8400-837e05258384">

If I click through on a yaml element for it's definition, the v3 schema is still shown, although I don't know where/how this is being sourced

<img width="1157" alt="image" src="https://github.com/GoogleContainerTools/skaffold/assets/1561613/a83828b4-7d38-4044-bba1-e26bf7e3e6d8">

**Comment by MuhamedUsman** [comment]
Adding this to the top of your yaml helps

```yaml
# nonk8s
# yaml-language-server: $schema=https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/docs-v2/content/en/schemas/v4beta13.json
```
